/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi;

import org.junit.Test;

public class HotelReservationTest {
	@Test
	public void testSomeLibraryMethod() {

	}
}
