/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi;

public class HotelReservation {
	public static void main(String[] args) {
		System.out.println("Welcome to hotel reservation system!");
	}
}
